### ISSUE TITLE
按照 安装指南.pdf 步骤操作，执行到【python3 manage.py createsuperuser】报错

### ISSUE THREAD

**Issue by GitHub-fort** [zhaoweiho/SecurityManageFramwork#1]
报错内容如下：

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line                                       487, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line                                       403, in get
    self.model._meta.object_name
RBAC.models.DoesNotExist: Profile matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", lin                                      e 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.p                                      y", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.auth_user__old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.p                                      y", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.p                                      y", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py",                                       line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/management/co                                      mmands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py",                                       line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/management/co                                      mmands/createsuperuser.py", line 179, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user                                      _data)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/models.py", l                                      ine 161, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/models.py", l                                      ine 144, in _create_user
    user.save(using=self._db)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/base_user.py"                                      , line 73, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 7                                      29, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 7                                      69, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", l                                      ine 178, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", l                                      ine 178, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/root/SeMF/SecurityManageFramwork/RBAC/models.py", line 115, in create_u                                      ser_profile
    Profile.objects.get_or_create(user=instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", lin                                      e 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line                                       489, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line                                       521, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line                                       417, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 7                                      29, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 7                                      59, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, upda                                      te_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 8                                      42, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 8                                      80, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", lin                                      e 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line                                       1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py"                                      , line 1284, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", lin                                      e 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", lin                                      e 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._e                                      xecute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", lin                                      e 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", lin                                      e 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in                                       __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", lin                                      e 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.p                                      y", line 303, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main.auth_user__old

**Comment by apolloduan** [comment]
Django2.0.4有bug，卸载Django重新安装2.1.7，重新部署系统后createsuperuser执行成功。
